openapi: 3.0.0
info:
  title: BCIToriApi
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  Get all items:
    parameters: []
    get:
      summary: ''
      operationId: get-api-items
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/item'
      description: Get all items
  '/api/items/{id}':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  username:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  category:
                    type: string
                  location:
                    type: string
                  price:
                    type: number
                  date:
                    type: string
                  delivery-type:
                    type: string
                  telephone:
                    type: string
                  image:
                    type: object
                required:
                  - id
        '404':
          description: Item with the given ID was not found
      operationId: 'get-api-items-:id'
      description: Get item with given ID
    delete:
      summary: ''
      operationId: 'delete-api-items-:id'
      responses:
        '200':
          description: OK
        '404':
          description: Item with the given ID was not found
      description: Delete item with given ID
    put:
      summary: ''
      operationId: 'put-api-items-:id'
      responses:
        '200':
          description: OK
        '404':
          description: Item with the given ID was not found
      description: Update item with given ID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                '':
                  type: string
        description: ''
    parameters:
      - schema: {}
        name: id
        in: path
        required: true
        description: 'Item ID '
components:
  schemas:
    item:
      title: item
      type: object
      description: ''
      x-examples:
        example-1:
          id: '701'
          username: Rauno59
          title: Gibson guitar
          description: Selling nice Les Paul from 1985
          category: Hobby
          location: Oulu
          price: 1300
          date: '2019-08-24T14:15:22Z'
          delivery-type: Shipping or pickup
          telephone: '0401231231'
          image: {}
      properties:
        id:
          type: integer
          description: Item ID will be generated at listing.
        username:
          type: string
          description: Item seller's username
        title:
          type: string
          description: Sell ad title
        description:
          type: string
          description: Item description
        category:
          type: string
          description: Item category
        location:
          type: string
          description: Item location
        price:
          type: number
          description: Selling price
        date:
          type: string
          description: Date when sale id was created
          format: date-time
        deliverytype:
          type: string
          description: Delivery shipping or pickup
        telephone:
          type: string
          description: Seller's telephone number
        image:
          type: object
          maxProperties: 4
      required:
        - id
        - username
        - title
        - description
        - category
        - location
        - price
        - date
        - deliverytype
        - telephone
    user:
      title: user
      type: object
      x-examples:
        example-1:
          id: 123123
          username: Rauno59
          password: pa$$word
          email: user@example.com
      properties:
        id:
          type: integer
        username:
          type: string
          minLength: 5
        password:
          type: string
          format: password
        email:
          type: string
          format: email
      required:
        - id
        - username
        - password
        - email
  securitySchemes: {}
